spring:
    profiles:
        active: ${ENVIRONMENT}
    datasource:
        # driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: ${DDL_AUTO}
        show-sql: ${SHOW_SQL}
        properties:
            hibernate:
                format_sql: true
        # database: postgresql
        # database-platform: org.hibernate.dialect.PostgreSQLDialect